[project]
name = 'Decentralized-Transportation-Mobility-as-a-Service'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.journey-planning]
path = 'contracts/journey-planning.clar'
clarity_version = 2
epoch = 2.5

[contracts.payment-integration]
path = 'contracts/payment-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-provider-verification]
path = 'contracts/service-provider-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
